//
//  SearchModels.swift
//  iMusic
//
//  Created by Роман on 07.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    
    enum Model {
        struct Request {
            enum RequestType {
                case some
            }
        }
        struct Responce {
            enum ResponceType {
                case some
            }
        }
        struct ViewModel {
            enum ViewModelData {
                case some
            }
        }
    }
    
}
